### ISSUE TITLE
Potential error in SQLite Files in the App Bundle section

### ISSUE THREAD

**Issue by mmorey** [objcio/issue-4-importing-and-fetching#1]
According to the [docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSFileManager_Class/Reference/Reference.html#//apple_ref/doc/uid/20000305-SW89) I believe `enumeratorAtURL:includingPropertiesForKeys:options:errorHandler:` gives you `NSURL` objects, not `NSString` paths as currently shown in the [SQLite Files in the App Bundle](http://www.objc.io/issue-4/importing-large-data-sets-into-core-data.html) section of this article.

So the example:

``` objective-c
for (NSString *path in enumerator) {
    // Delete .sqlite file and auxiliary files
}
```

Should probably be:

``` objective-c
for (NSURL *URL in enumerator) {
    // Delete .sqlite file and auxiliary files
}
```

Or am I mistaken?

**Comment by floriankugler** [comment]
Sorry, I forgot about this one. Should be fixed now!
